var Lista3 = [
  { NAME: "🍿REHÉN", URL: "https://h5.swplayer.com/es/detail/movie/AW4PZOVWYIx8tJ77jlZ0t-iHostage" },
  { NAME: "🍿DESTINO FINAL 5", URL: "https://h5.swplayer.com/es/detail/movie/CYsCn78yRPHVcBAb9W5Qo-Final-Destination-5" },
  { NAME: "🍿BORDERLANDS", URL: "https://h5.swplayer.com/es/detail/movie/tT06q3HHM52YQFyLdL3ID-Borderlands" }, 
  { NAME: "🍿EL MAGO DE OZ", URL: "https://h5.swplayer.com/es/detail/movie/FXC1Hga5ZJbOyRFCQqf9r-Oz-the-Great-and-Powerful" },
  { NAME: "🍿BLANCA NIEVES Y EL CAZADOR", URL: "https://h5.swplayer.com/es/detail/movie/VL4maC5zLJ6a2K6IcpEH0-The-Huntsman-Winters-War" }, 
  { NAME: "🍿PIRATAS DEL CARIBE 5", URL: "https://h5.swplayer.com/es/detail/movie/XBGdIGVjA4k9YFoCsCccS-Pirates-of-the-Caribbean-Dead-Men-Tell-No-Tales" },
  { NAME: "🍿VAN HELSING", URL: "https://h5.swplayer.com/es/detail/movie/71525-Van-Helsing" }, 
  { NAME: "🍿CAPITANA MARVEL", URL: "https://h5.swplayer.com/es/detail/movie/26196-Captain-Marvel" },
  { NAME: "🍿CAPITAN AMERICA CIVIL WAR", URL: "https://h5.swplayer.com/es/detail/movie/ns3tAK9y41JckBsDQDbPw-Captain-America-Civil-War" }, 
  { NAME: "🍿IRON MAN 3", URL: "https://h5.swplayer.com/es/detail/movie/IsvtVMq5BIjjWfLUSGQQf-Iron-Man-3" },
  { NAME: "🍿SUPERMAN", URL: "https://h5.swplayer.com/es/detail/movie/INpRKzoLtlOSCVg8spbbS-Superman" },
  { NAME: "🍿NO TE MUEVAS", URL: "https://h5.swplayer.com/es/detail/movie/RTqRuq5EiUmkylDF6ZaT0-Dont-Move" }, 
  { NAME: "🍿JUEGO DE TRONOS", URL: "https://lamovie.github.io/CONTENIDO/GAME%20OF%20THRONES.html" },  
  { NAME: "🍿TIERRA DE MAFIA", URL: "https://lamovie.github.io/CONTENIDO/TIERRA%20DE%20MAFIA.html" }, 
  { name: "🍿FUTURAMA FULL", url: "https://h5.swplayer.com/es/detail/drama/tHa42lElZ3P8PDRyZbtEo-Futurama-Season-1/1" },
  { name: "🍿LA CASA DE PAPEL", url: "https://h5.swplayer.com/es/detail/drama/w4T1wpuJxUu5b0bHfQnU5-Money-Heist-Season-1" },
  { name: "🍿FAMILY GUY", url: "https://h5.swplayer.com/es/detail/drama/QTUVOLeIYWjsO8Fv2PcxM-Family-Guy-Season-1" },
  { name: "🍿NARUTO", url: "https://h5.swplayer.com/es/detail/drama/GGCScosEDKZxW5ejPWH9n-Naruto%5BAudio-Latino%5D" },
  { name: "🍿OUTLANDER", url: "https://h5.swplayer.com/es/detail/drama/SC5e4d5u7ZQBPnkhz675G-Outlander-Season-1/1" },
  { name: "🍿THE WALKING DEAD", url: "https://h5.swplayer.com/es/detail/drama/Gr410ksu2cfhFfQP75H9j-The-Walking-Dead-Season-1" },
  { name: "🍿LOS SIMPSONS", url: "https://h5.swplayer.com/es/detail/drama/MNxoJpARCrPHvVPu1ljH1-The-Simpsons-Season-1" },
  { name: "🍿ONE PIECE", url: "https://h5.swplayer.com/es/detail/drama/vdXAbbyiZgaslQlAZ9Z6H-One-Piece" },
  { name: "🍿DESTINO FINAL", url: "https://h5.swplayer.com/es/detail/movie/kL3SvPkWfniVKPIPhXcdc-Final-Destination" },
  { name: "🍿VIS A VIS", url: "https://h5.swplayer.com/es/detail/drama/br2opIQsBK8hepOpdQEDI-Vis-a-vis-Season-1" },
  { name: "🍿MY HERO ACADEMIA", url: "https://h5.swplayer.com/detail/drama/C1lUW7UsRxfbGSHuD2Vax-My-Hero-Academia%5BAudio-Latino%5D/1" },
  { name: "🍿VIKINGOS", url: "https://h5.swplayer.com/es/detail/drama/3TVD1tXGJbNUvPc0u3mP8-Vikings-Season-1/1" },
  { name: "🍿EVIL", url: "https://h5.swplayer.com/es/detail/drama/ddsgdunU4e2xi7R5NT3K4-Evil-Season-1" },
  { name: "🍿THE LAST OF US", url: "https://h5.swplayer.com/es/detail/drama/rvYsv23lPziLIw5oz2KjV-The-Last-of-Us-Season-1%5BAudio-Latino%5D/1" },  
  { NAME: "🍿KARMA", URL: "https://youtu.be/TkZsog3y-FU?si=VJgFBVKCG645oI0k" },
  { NAME: "🍿DIRK GENTLY", URL: "https://ver.123pelicula.com/es/detail/drama/9BmxQONumy1KNNbbmGpt0-Dirk-Gentlys-Holistic-Detective-Agency-Season-1/1" }, 
  { NAME: "🍿", URL: "" },
  { NAME: "🍿", URL: "" }, 
  { NAME: "🍿", URL: "" },
  { NAME: "🍿", URL: "" }, 
  { NAME: "🍿", URL: "" },
  { NAME: "🍿", URL: "" }, 
  { NAME: "🍿", URL: "" },
  { NAME: "🍿", URL: "" }, 
  { NAME: "🍿", URL: "" },
  { NAME: "🍿", URL: "" }, 
  { NAME: "🍿", URL: "" },
  { NAME: "🍿", URL: "" }, 
  { NAME: "🍿", URL: "" },
  { NAME: "🍿", URL: "" }, 
  { NAME: "🍿", URL: "" },
  { NAME: "🍿", URL: "" }, 
  { NAME: "🍿", URL: "" },
  { NAME: "🍿", URL: "" }, 
  { NAME: "🍿", URL: "" },
  { NAME: "🍿", URL: "" }, 
  { NAME: "🍿", URL: "" },
  { NAME: "🍿", URL: "" }, 
  { NAME: "🍿", URL: "" },
  { NAME: "🍿", URL: "" }, 
  { NAME: "🍿", URL: "" },
  { NAME: "🍿", URL: "" }, 
  { NAME: "🍿", URL: "" },
  { NAME: "🍿", URL: "" }, 
  { NAME: "🍿", URL: "" },
  { NAME: "🍿", URL: "" }, 
  { NAME: "🍿", URL: "" },
  { NAME: "🍿", URL: "" }, 
  { NAME: "🍿", URL: "" },
  { NAME: "🍿", URL: "" }
]
  
  
  
  
 
  
  
